pipeline { 
     agent any 
      
     stages { 
         stage('Checkout') {  
             steps {
                 sh" checkout Project repo"
                 git credentialsId: "${github_creds}" , url: "${project_repo}"
                 script {
                    if(${test_repo} != "None"){
                         git credentialsId: "${github_creds}" , url: "${test_repo}"
                    }
                }
             } 
         } 
         stage('Build') {  
             steps {
                  script {
                    if(${custom_build} == false){
                      sh 'echo Hello World'
                    }
                    else{
                      sh 'echo Hello Smart World'
                    }
                 }
             } 
         } 
     } 
  
     post { 
  
       // Email Ext plugin:  
       success {   
          
         emailext ( 
             subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'", 
             body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p> 
               <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""", 
             to: "${emailRecipient}", 
             from: "buildNotifications@emailaddress.com" 
           ) 
       } 
  
       failure { 
          
         emailext ( 
             subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'", 
             body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p> 
               <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""", 
             to: "${emailRecipient}", 
             from: "buildNotifications@emailaddress.com" 
           ) 
       } 
   } 
 } 
